repos:
  - repo: https://github.com/executablebooks/mdformat
    rev: 1.0.0
    hooks:
      - id: mdformat
        args: [--wrap, "no"]
        additional_dependencies:
          - mdformat-gfm==1.0.0
          - mdformat-frontmatter==2.1.2
        exclude: >-
          (?x)^(
            .*?/\.venv/|
            .*?/runs/|
            .*?/data/|
            .*?/omni_recipe/|
            .*?/third_party/|
            .*?/archive/|
            .*?/archived/|
            .*?/modelcard_template\.md$
          )
