model:
  name: "omniASR_CTC_300M_v2"

dataset:
  name: "peacock_librispeech_phone_manifest_v1"
  train_split: "train"
  valid_split: "dev"
  storage_mode: "MANIFEST"
  task_mode: "ASR"
  manifest_storage_config:
    read_text: true
    cached_fd_count: 1000
  asr_task_config:
    min_audio_len: 32000
    max_audio_len: 960000
    max_num_elements: 960000
    batch_shuffle_window: 1
    example_shuffle_window: 1
    normalize_audio: true

tokenizer:
  name: "omniASR_tokenizer_arpabet_41_v1"

optimizer:
  config:
    lr: 1e-05

trainer:
  freeze_encoder_for_n_steps: 0
  mixed_precision:
    dtype: "torch.bfloat16"
  grad_accumulation:
    num_batches: 4

regime:
  num_steps: 5000
  validate_every_n_steps: 500
  validate_after_n_steps: 500
  checkpoint_every_n_steps: 500
  checkpoint_after_n_steps: 500
  publish_metrics_every_n_steps: 500
  publish_metrics_after_n_steps: 500
